version: "3.8"

services:
    nginx:
        container_name: nginx
        image: nginx:1.20.0
        ports:
            - 80:80
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./app:/var/www/html
        networks:
            - net-lnmp
    
    php:
        container_name: php
        build: php
        volumes:
            - ./app:/var/www/html
        networks:
            - net-lnmp
  
    maraidb:
        container_name: maraidb
        image: mariadb:10.6.0
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mariadb:/var/lib/mysql 
        networks:
            - net-lnmp

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5.1.0
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        networks:
            - net-lnmp

    redis:
        container_name: redis
        image: redis:6.2-alpine
        ports:
            - 6379:6379
        networks:
            - net-lnmp


networks: 
    net-lnmp:
        external: true